wso2/oxygen-ui

README.md
=> docs(readme): add workflow labels

packages/react/.storybook/main.js, packages/react/.storybook/preview.tsx, packages/react/.storybook/theme.js, packages/react/package.json, pnpm-lock.yaml
The `Storybook` theme switcher was not working properly.
- N/A
- N/A
=> chore(react): fix theme switch in Storybook

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/doc_issues.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement.md, .github/ISSUE_TEMPLATE/test_request.md
Add GitHub issue templates.
- N/A
- N/A
=> chore: add ISSUE TEMPLATE

packages/react/.storybook/story-config.ts, packages/react/src/components/IconButton/IconButton.stories.mdx, packages/react/src/components/IconButton/IconButton.tsx, packages/react/src/components/IconButton/__tests__/IconButton.test.tsx, packages/react/src/components/IconButton/__tests__/__snapshots__/IconButton.test.tsx.snap, packages/react/src/components/IconButton/icon-button.scss, packages/react/src/components/IconButton/index.ts
Wrap `IconButton` component from MUI.
- N/A
=> feat(react): add `IconButton` component

packages/react/src/components/ActionCard/__tests__/__snapshots__/ActionCard.test.tsx.snap, packages/react/src/components/Button/Button.tsx, packages/react/src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap, packages/react/src/components/Button/button.scss, packages/react/src/components/Header/__tests__/__snapshots__/Header.test.tsx.snap, packages/react/src/components/SignIn/__tests__/__snapshots__/SignIn.test.tsx.snap, packages/react/src/components/UserDropdownMenu/__tests__/__snapshots__/UserDropdownMenu.test.tsx.snap, packages/react/src/theme/default-theme.ts
The following variants have been added to the Button component:
1. Gradient
2. Gray
3. Rounded
=> feat(react): Add new variants of the Button component

packages/react/.storybook/story-config.ts, packages/react/src/components/Badge/Badge.stories.mdx, packages/react/src/components/Badge/Badge.tsx, packages/react/src/components/Badge/__tests__/Badge.test.tsx, packages/react/src/components/Badge/__tests__/__snapshots__/Badge.test.tsx.snap, packages/react/src/components/Badge/badge.scss, packages/react/src/components/Badge/index.ts
=> feat(react): add `Badge` component

packages/react/.storybook/story-config.ts, packages/react/src/components/Footer/Footer.stories.mdx, packages/react/src/components/Footer/Footer.tsx, packages/react/src/components/Footer/__tests__/Footer.test.tsx, packages/react/src/components/Footer/__tests__/__snapshots__/Footer.test.tsx.snap, packages/react/src/components/Footer/footer.scss, packages/react/src/components/Footer/index.ts, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
Add `Footer`  component to Oxygen UI component library.
*Dark*
*Light*
- N/A
=> feat(react): add `Footer` component

packages/react/src/components/ActionCard/ActionCard.tsx, packages/react/src/components/ActionCard/__tests__/__snapshots__/ActionCard.test.tsx.snap, packages/react/src/components/ActionCard/action-card.scss, packages/react/src/components/AppBar/__tests__/__snapshots__/AppBar.test.tsx.snap, packages/react/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap, packages/react/src/components/Header/__tests__/__snapshots__/Header.test.tsx.snap, packages/react/src/components/ListItemText/__tests__/__snapshots__/ListItemText.test.tsx.snap, packages/react/src/components/MenuItem/__tests__/__snapshots__/MenuItem.test.tsx.snap, packages/react/src/components/Navbar/__tests__/__snapshots__/Navbar.test.tsx.snap, packages/react/src/components/SignIn/__tests__/__snapshots__/SignIn.test.tsx.snap, packages/react/src/components/TextField/__test__/__snapshots__/TextField.test.tsx.snap, packages/react/src/components/Typography/__tests__/__snapshots__/Typography.test.tsx.snap, packages/react/src/theme/default-theme.ts, packages/react/src/theme/extend-theme.ts
This extracts out the scss styling and places it in the default theme
=> chore(react): improve ActionCard component

packages/react/.storybook/story-config.ts, packages/react/src/components/CircularProgress/CircularProgress.stories.mdx, packages/react/src/components/CircularProgress/CircularProgress.tsx, packages/react/src/components/CircularProgress/__tests__/CircularProgress.test.tsx, packages/react/src/components/CircularProgress/__tests__/__snapshots__/CircularProgress.test.tsx.snap, packages/react/src/components/CircularProgress/circular-progress.scss, packages/react/src/components/CircularProgress/index.ts
Add `CircularProgress` or spinner component.
- None
=> feat(react): add `CircularProgress` component

packages/react/.storybook/story-config.ts, packages/react/src/components/AppShell/AppShell.stories.mdx, packages/react/src/components/AppShell/AppShell.tsx, packages/react/src/components/AppShell/__tests__/AppShell.test.tsx, packages/react/src/components/AppShell/__tests__/__snapshots__/AppShell.test.tsx.snap, packages/react/src/components/AppShell/app-shell.scss, packages/react/src/components/AppShell/index.ts, packages/react/src/components/Footer/Footer.stories.mdx, packages/react/src/components/Header/Header.stories.mdx, packages/react/src/components/Header/Header.tsx, packages/react/src/components/Header/__tests__/__snapshots__/Header.test.tsx.snap, packages/react/src/components/Header/header.scss, packages/react/src/components/Navbar/navbar.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
Add `AppShell`  component to Oxygen UI component library.
*Dark*
*Light*
- N/A
=> feat(react): add `AppShell` component

packages/react/.storybook/story-config.ts, packages/react/src/components/ActionCard/__tests__/__snapshots__/ActionCard.test.tsx.snap, packages/react/src/components/Card/__tests__/__snapshots__/Card.test.tsx.snap, packages/react/src/components/Stepper/Stepper.stories.mdx, packages/react/src/components/Stepper/Stepper.tsx, packages/react/src/components/Stepper/__tests__/Stepper.test.tsx, packages/react/src/components/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/react/src/components/Stepper/index.ts, packages/react/src/components/Stepper/stepper.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
https://user-images.githubusercontent.com/20745428/220350337-ed1bf467-3a51-48bb-87d1-33e32fc2072f.mov
This PR adds the `Stepper` component that allows to slide through the steps passed as a prop.
=> feat(react): add Stepper component

packages/react/.storybook/story-config.ts, packages/react/src/components/Box/Box.tsx, packages/react/src/components/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/react/src/components/Wizard/Wizard.stories.mdx, packages/react/src/components/Wizard/Wizard.tsx, packages/react/src/components/Wizard/index.ts, packages/react/src/components/Wizard/wizard.scss
This PR introduces the `Wizard` component that can be used to break down user flows step by step.
=> feat(react): add Wizard component

packages/react/.storybook/story-config.ts, packages/react/src/components/LinearProgress/LinearProgress.stories.mdx, packages/react/src/components/LinearProgress/LinearProgress.tsx, packages/react/src/components/LinearProgress/__test__/LinerProgress.test.tsx, packages/react/src/components/LinearProgress/__test__/__snapshots__/LinerProgress.test.tsx.snap, packages/react/src/components/LinearProgress/index.ts, packages/react/src/components/LinearProgress/linear-progress.scss
This PR adds the `LinearProgress` component.
=> feat(react): add LinearProgress component

packages/react/src/components/ActionCard/__tests__/__snapshots__/ActionCard.test.tsx.snap, packages/react/src/components/SignIn/__tests__/__snapshots__/SignIn.test.tsx.snap, packages/react/src/theme/default-theme.ts
This PR updates the styling of the `Button` component.
=> chore(react): update Button styling

packages/react/src/components/ActionCard/ActionCard.tsx, packages/react/src/components/ActionCard/__tests__/__snapshots__/ActionCard.test.tsx.snap, packages/react/src/components/Carousel/Carousel.stories.mdx, packages/react/src/components/Stepper/Stepper.stories.mdx, packages/react/src/components/Wizard/Wizard.stories.mdx, packages/react/src/components/Wizard/Wizard.tsx
This PR replaces the imported Mui components with wrapped components and fixes minor doc issues.
=> chore(react): import wrapped components and fix doc issues

packages/react/src/components/IconButton/IconButton.tsx, packages/react/src/components/IconButton/icon-button.scss
This PR adds two variants, namely `contained` and `text` to `IconButton`. 
=> chore(react): add variant to IconButton

packages/react/src/components/Breadcrumbs/Breadcrumbs.stories.mdx, packages/react/src/components/Typography/Typography.stories.mdx
$subject due to mdx syntax errors.
- N/A
- N/A
=> chore(react): fix storybook runtime

.github/workflows/builder.yml, .github/workflows/pr-builder.yml
=> ci(github): validate storybook build in CI

packages/react/src/components/Carousel/Carousel.tsx, packages/react/src/components/Footer/Footer.tsx, packages/react/src/components/Header/Header.tsx, packages/react/src/hooks/index.ts, packages/react/src/hooks/use-is-mobile.tsx
This PR introduces the `useIsMobile` hook that returns a `Boolean` specifying if the current view is mobile or not. 
=> feat(react): add useIsMobile hook

packages/react/src/components/Carousel/Carousel.tsx, packages/react/src/components/Stepper/Stepper.tsx
This PR fixes the issues with the key prop in the `Carousel` component. 
=> chore(react): fix Carousel key issue

packages/react/.storybook/story-config.ts, packages/react/src/components/Tab/Tab.stories.mdx, packages/react/src/components/Tab/Tab.tsx, packages/react/src/components/Tab/__tests__/Tab.test.tsx, packages/react/src/components/Tab/__tests__/__snapshots__/Tab.test.tsx.snap, packages/react/src/components/Tab/index.ts, packages/react/src/components/Tab/tab.scss
=> feat(react): add `Tab` component

packages/react/.storybook/story-config.ts, packages/react/src/components/Tabs/Tabs.stories.mdx, packages/react/src/components/Tabs/Tabs.tsx, packages/react/src/components/Tabs/__test__/Tabs.test.tsx, packages/react/src/components/Tabs/__test__/__snapshots__/Tabs.test.tsx.snap, packages/react/src/components/Tabs/index.ts, packages/react/src/components/Tabs/tabs.scss
=> feat(react): add `Tabs` component

packages/react/src/components/Tabs/Tabs.stories.mdx
> $subject
Updated story:
- N/A
- N/A
=> chore(react): add `TabPanel` component to `Tabs` component story

packages/react/package.json, pnpm-lock.yaml
=> chore(react): add `@storybook/addon-essentials` as a dev dependancy

packages/react/src/components/Navbar/navbar.scss, packages/react/src/theme/default-theme.ts
Fix the minor differences in the width and padding used in the design vs implementation of the `Navbar`
- None
- None
=> chore(react): fix `Navbar` styles to match design

.github/workflows/release.yml, .release-it.js, CONTRIBUTING.md, README.md, VERSIONING_POLICY.md, docs/README.md, docs/package.json, examples/multi-brand-identity/README.md, examples/multi-brand-identity/package.json, package.json, packages/logger/README.md, packages/logger/package.json, packages/primitives/README.md, packages/primitives/package.json, packages/react-icons/README.md, packages/react-icons/package.json, packages/react/README.md, packages/react/package.json, pnpm-lock.yaml, release/templates/header.hbs, release/templates/template.hbs
Prepare for the initial release of Oxygen UI.
POC's with [Changesets](https://github.com/changesets/changesets/issues), [Auto](https://intuit.github.io/auto/) & [Semantic Release](https://github.com/semantic-release/semantic-release) was done on a personal [fork](https://github.com/brionmario/oxygen-ui/pulls?q=is%3Apr+is%3Aclosed).
-  ✅ Automate the release with [`release-it`](https://github.com/release-it/release-it)
-  ✅ Cut a GitHub release & Generate Changelogs.
-  ✅ Create a versioning strategy document. ([VERSIONING_POLICY.md](https://github.com/brionmario/oxygen-ui/blob/prepare-for-release/VERSIONING_POLICY.md))
- None
- None
- https://github.com/brionmario/oxygen-ui/blob/prepare-for-release/VERSIONING_POLICY.md
=> chore: prepare for the initial release

.release-it.js
$subject to try to fix release workflow.
- None
- None
=> chore(release): skip npm checks in `@release-it-plugins/workspaces`

.github/workflows/release.yml
=> ci(github): update bot git configs

.github/workflows/release.yml
=> ci(github): update release workflow

README.md
=> docs: update changelog section

docs/website/pages/index.tsx, examples/multi-brand-identity/package.json, examples/multi-brand-identity/src/branding/themes/ballerina.ts, examples/multi-brand-identity/src/branding/themes/choreo.ts, examples/multi-brand-identity/src/branding/themes/default.ts, packages/react/.storybook/theme.js
Multi-brand example was broken due to the gradient button introduction.
- N/A
- N/A
=> fix(docs): fix multi-brand sample issues & navigation brand click navigation issues in storybook

docs/website/pages/index.tsx
=> chore(docs): fix link

packages/react/src/components/AppBar/AppBar.stories.mdx
$subject
- https://github.com/wso2/oxygen-ui/issues/98
- None
=> chore(react): add sample content to `AppBar`

packages/react/src/components/Header/Header.stories.mdx, packages/react/src/components/Header/header.scss, packages/react/src/components/UserDropdownMenu/UserDropdownMenu.tsx, packages/react/src/components/UserDropdownMenu/user-dropdown-menu.scss, packages/react/src/theme/default-theme.ts
Fix padding/spacing and match to the design in `Header` and `UserDropdownMenu`
- Implementation
- https://github.com/wso2/oxygen-ui/issues/96
- None
=> chore(react): fix spacing in `Header` and `UserDropdownMenu`

packages/react/.storybook/story-config.ts, packages/react/src/components/Accordion/Accordion.stories.mdx, packages/react/src/components/Accordion/Accordion.tsx, packages/react/src/components/Accordion/__tests__/Accordion.test.tsx, packages/react/src/components/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap, packages/react/src/components/Accordion/accordion.scss, packages/react/src/components/Accordion/index.ts
Wrap `Accordion` component
- https://github.com/wso2/oxygen-ui/issues/103
- None
=> feat(react): add `Accordion` component

packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/navbar.scss, packages/react/src/theme/default-theme.ts
- https://github.com/wso2/oxygen-ui/issues/96
- None
=> chore(react): improve `Navbar` styles

packages/react/src/components/TextField/text-field.scss
$subject
- Light theme
- Dark theme
=> chore(react): fix password criteria tooltip styles

packages/react/.storybook/story-config.ts, packages/react/src/components/Snackbar/Snackbar.stories.mdx, packages/react/src/components/Snackbar/Snackbar.tsx, packages/react/src/components/Snackbar/__tests__/Snackbar.test.tsx, packages/react/src/components/Snackbar/__tests__/__snapshots__/Snackbar.test.tsx.snap, packages/react/src/components/Snackbar/index.ts, packages/react/src/components/Snackbar/snackbar.scss
This wraps the MUI `Snackbar` component. 
=> feat(react): add Snackbar component

packages/react/.storybook/story-config.ts, packages/react/src/components/Alert/Alert.stories.mdx, packages/react/src/components/Alert/Alert.tsx, packages/react/src/components/Alert/__tests__/Alert.test.tsx, packages/react/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap, packages/react/src/components/Alert/alert.scss, packages/react/src/components/Alert/index.ts, packages/react/src/components/AlertTitle/AlertTitle.stories.mdx, packages/react/src/components/AlertTitle/AlertTitle.tsx, packages/react/src/components/AlertTitle/__tests__/AlertTitle.test.tsx, packages/react/src/components/AlertTitle/__tests__/__snapshots__/AlertTitle.test.tsx.snap, packages/react/src/components/AlertTitle/alert-title.scss, packages/react/src/components/AlertTitle/index.ts
This wraps the `Alert` MUI component. 
=> feat(react): add Alert component

packages/react/src/components/Navbar/index.ts
This PR exports the `NavbarItem` type
=> chore(react): export NavbarItem type

packages/react/src/components/Snackbar/Snackbar.tsx
This PR forwards `Ref` to `Snackbar` component. 
=> chore(react): forward Ref to Snackbar

packages/react/src/components/AppShell/AppShell.stories.mdx, packages/react/src/components/CircularProgress/CircularProgress.stories.mdx, packages/react/src/components/Header/header.scss, packages/react/src/components/LinearProgress/LinearProgress.stories.mdx, packages/react/src/components/Navbar/Navbar.stories.mdx, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/theme/default-theme.ts
Fix
- Fix `AppShell` Story as the interface of `NavbarItems` was updated to extend for headings.
- Add min-height of `Header` from the default theme.
- Improve progress component stories.
- None
- None
=> chore(react): `AppShell` Story and styling fixes

packages/react/scripts/fix-files.js, packages/react/src/components/AppBar/__tests__/__snapshots__/AppBar.test.tsx.snap, packages/react/src/components/AppShell/AppShell.stories.mdx, packages/react/src/components/AppShell/AppShell.tsx, packages/react/src/components/AppShell/__tests__/__snapshots__/AppShell.test.tsx.snap, packages/react/src/components/AppShell/app-shell.scss, packages/react/src/components/Header/Header.tsx, packages/react/src/components/Header/__tests__/__snapshots__/Header.test.tsx.snap, packages/react/src/components/Header/header.scss, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/navbar.scss, packages/react/src/components/UserDropdownMenu/UserDropdownMenu.tsx, packages/react/src/components/UserDropdownMenu/user-dropdown-menu.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
This PR updates the styling of components. 
=> chore(react): update component stylings

packages/react/src/components/Alert/Alert.tsx, packages/react/src/components/AlertTitle/AlertTitle.tsx, packages/react/src/components/AppShell/AppShell.stories.mdx, packages/react/src/components/Footer/Footer.stories.mdx, packages/react/src/components/Header/Header.stories.mdx, packages/react/src/components/Menu/Menu.stories.mdx, packages/react/src/components/Navbar/Navbar.stories.mdx, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/navbar.scss, packages/react/src/components/Snackbar/Snackbar.tsx, packages/react/src/components/Tab/Tab.stories.mdx, packages/react/src/components/UserDropdownMenu/UserDropdownMenu.tsx
The active indicator added to the Navbar:
=> chore(react): fix console errors and an active indicator to the Navbar

packages/react/src/components/Header/Header.tsx
> This PR exposes the `triggerOptions` prop of the `UserDropdownMenu` component through the `Header` component. 
=> chore(react): expose triggerOptions of UserDropdownMenu

packages/react/src/components/Header/Header.tsx, packages/react/src/components/UserDropdownMenu/UserDropdownMenu.tsx
>This PR fixes a typo in the `UserDropdownMenu` action button and updates the type of `triggerOptions`.
=> chore(react): fix typos and update type

packages/react/src/components/AppShell/app-shell.scss, packages/react/src/components/Header/Header.tsx
=> chore(react): remove Header UserDropdownMenu props default

packages/react/src/components/Navbar/Navbar.stories.mdx, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/navbar.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
=> chore(react): add tag to Navbar MenuItem

packages/react/src/components/Chip/chip.scss, packages/react/src/components/MenuItem/menu-item.scss, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/navbar.scss, packages/react/src/components/UserDropdownMenu/user-dropdown-menu.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
=> feat(react): Add status colors to Chip component

packages/react/src/components/Chip/chip.scss
=> chore(react): update Chip text style

packages/react/src/components/Header/header.scss
=> chore(react): remove header logo on hover text decoration

.release-it.js, packages/react/package.json, packages/react/scripts/build-components.js
=> ci(react): release from the dist folder of the react package and copy readme file into the dist folder

packages/react/package.json
=> fix(react): fix dist folder not being published

.github/workflows/pr-builder.yml, CONTRIBUTING.md, packages/react/README.md, packages/react/package.json, pnpm-lock.yaml
When working with the `@oxygen-ui/react` package in a project, we should be able to locally link the package to test the changes.
- Fixes https://github.com/wso2/oxygen-ui/issues/136
- N/A
=> chore(react): add watch mode build script & document local linking strategy

docs/website/package.json, pnpm-lock.yaml
=> chore(primitives): update next package version

packages/react/.storybook/story-config.ts, packages/react/src/components/Backdrop/Backdrop.stories.mdx, packages/react/src/components/Backdrop/Backdrop.tsx, packages/react/src/components/Backdrop/__tests__/Backdrop.test.tsx, packages/react/src/components/Backdrop/__tests__/__snapshots__/Backdrop.test.tsx.snap, packages/react/src/components/Backdrop/backdrop.scss, packages/react/src/components/Backdrop/index.ts
=> feat(react): add `Backdrop` component

README.md
> Update documentation link in the README file.
https://wso2.github.io/oxygen-ui/
- None
- None
=> docs(docs-infra): update readme

packages/react/.storybook/preview.tsx
=> chore(react): fix theme in component stories

.gitignore, packages/react-icons/README.md
=> Add link to icons page in react-icons package readme

packages/react/.storybook/story-config.ts, packages/react/src/components/Chip/chip.scss, packages/react/src/components/CollapsibleNavbarItem/CollapsibleNavbarItem.stories.mdx, packages/react/src/components/CollapsibleNavbarItem/CollapsibleNavbarItem.tsx, packages/react/src/components/CollapsibleNavbarItem/__tests__/CollapsibleNavbarItem.test.tsx, packages/react/src/components/CollapsibleNavbarItem/__tests__/__snapshots__/CollapsibleNavbarItem.test.tsx.snap, packages/react/src/components/CollapsibleNavbarItem/collapsible-navbar-item.scss, packages/react/src/components/CollapsibleNavbarItem/index.tsx, packages/react/src/components/Header/Header.tsx, packages/react/src/components/ListItemButton/ListItemButton.tsx, packages/react/src/components/Navbar/Navbar.stories.mdx, packages/react/src/components/Navbar/Navbar.tsx, packages/react/src/components/Navbar/__tests__/__snapshots__/Navbar.test.tsx.snap, packages/react/src/components/Navbar/navbar.scss, packages/react/src/components/NavbarItem/NavbarItem.stories.mdx, packages/react/src/components/NavbarItem/NavbarItem.tsx, packages/react/src/components/NavbarItem/__tests__/NavbarItem.test.tsx, packages/react/src/components/NavbarItem/__tests__/__snapshots__/NavbarItem.test.tsx.snap, packages/react/src/components/NavbarItem/index.tsx, packages/react/src/components/NavbarItem/navbar-item.scss, packages/react/src/components/Tooltip/Tooltip.tsx, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
- Add `CollapsibleNavbarItem` component
- Modularize navbar item related components and simplify implementation (`NavbarItem` and `CollapsibleNavbarItem`)
- Improve styling in Navbar
- Improve interfaces
`CollapsibleNavbarItem`
Collapsed
Expanded
- None
- None
=> feat(react): add CollapsibleNavbarItem component

packages/react/src/components/CollapsibleNavbarItem/CollapsibleNavbarItem.tsx, packages/react/src/components/Header/header.scss
=> chore(react): update props and styles

packages/react/src/components/AppShell/AppShell.stories.mdx, packages/react/src/components/Navbar/Navbar.stories.mdx
=> chore(react): update Navbar and Appshell stories

packages/react/.storybook/story-config.ts, packages/react/src/components/Accordion/Accordion.stories.mdx, packages/react/src/components/AccordionDetails/AccordionDetails.stories.mdx, packages/react/src/components/AccordionDetails/AccordionDetails.tsx, packages/react/src/components/AccordionDetails/__tests__/AccordionDetails.test.tsx, packages/react/src/components/AccordionDetails/__tests__/__snapshots__/AccordionDetails.test.tsx.snap, packages/react/src/components/AccordionDetails/index.ts, packages/react/src/components/AccordionSummary/AccordionSummary.stories.mdx, packages/react/src/components/AccordionSummary/AccordionSummary.tsx, packages/react/src/components/AccordionSummary/__tests__/AccordionSummary.test.tsx, packages/react/src/components/AccordionSummary/__tests__/__snapshots__/AccordionSummary.test.tsx.snap, packages/react/src/components/AccordionSummary/index.ts, packages/react/src/components/index.ts
- Add new components ✨
- AccordionSummary
- AccordionDetails
- N/A
=> feat(react): add `AccordionSummary` & `AccordionDetails` components

packages/react/src/components/Autocomplete/Autocomplete.tsx, packages/react/src/components/Autocomplete/index.ts
Fix type issue in autocomplete component.
=> fix(react): fix autocomplete component prop type issue

packages/react/src/components/Select/Select.stories.mdx, packages/react/src/components/Select/Select.tsx, packages/react/src/components/Select/select.scss
- Workaround for: https://github.com/wso2/oxygen-ui/issues/171
- N/A
=> fix(react): fix static label issues in `Select`

packages/react/src/components/CollapsibleNavbarItem/CollapsibleNavbarItem.tsx, packages/react/src/components/CollapsibleNavbarItem/collapsible-navbar-item.scss
=> chore(react): update font size of Navbar sub item

packages/primitives/src/icons/building-pen-16.svg
=> feat(primitives): add new icon

packages/react/src/components/Header/Header.tsx, packages/react/src/components/Header/header.scss
=> chore(react): update text style of Avatar in Header

packages/react/src/components/Switch/switch.scss
=> fix(react): add default styles for switch component

packages/react/src/components/DataGrid/__tests__/__snapshots__/DataGrid.test.tsx.snap, packages/react/src/theme/default-theme.ts
Remove the shadow set for elevation 0 paper in the default theme
=> fix(react): remove the default shadow

packages/primitives/src/icons/document-check-16.svg
Add `DocumentCheckIcon` 
- https://github.com/wso2/oxygen-ui/issues/203
=> feat(primitives): add DocumentCheckIcon

CONTRIBUTING.md
Add guidelines for PR and issue creation.
- https://github.com/wso2/oxygen-ui/issues/205
- N/A
=> docs: add PR and issue creation guidelines

packages/primitives/src/icons/download-16.svg
- Adds new icons related to download
- https://github.com/wso2/oxygen-ui/issues/213
- N/A
=> feat(primitives): add Download icons 

packages/react/src/components/Chip/chip.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
Update the design of the `Chip` component.
=> feat(react): update the design of the `Chip` component.

packages/react/src/components/Chip/chip.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
Add a new `coming-soon` chip design
=> feat(react): add a new `coming-soon` chip design

.release-it.js
build: update `.release-it.js` to fix the release action not passing
=> build: update `.release-it.js` to fix the release action not passing

.github/workflows/release.yml, pnpm-lock.yaml
build: stick `pnpm` version of the `release` action
=> build: stick`pnpm` version of the `release` action

packages/react/src/theme/default-theme.ts
chore: change premium colour in the premium chip
=> chore: change premium colour in the premium chip

packages/react/src/components/CollapsibleNavbarItem/collapsible-navbar-item.scss, packages/react/src/models/theme.ts, packages/react/src/theme/default-theme.ts
chore(react): Change the design of the oxygen chip in `collapsible-navbar-item`
=> chore(react): Change the design of the oxygen chip in `collapsible-navbar-item`

packages/react/src/components/Chip/chip.scss
chore(react): update the design of the default design of the chip component
=> chore(react): update the design of the default design of the chip component

packages/react/src/components/Chip/Chip.tsx, packages/react/src/components/Chip/chip.scss
Chore(react): remove border css property in the Chip component
=> Chore(react): remove border css property in the Chip component

packages/react/src/index.ts
To fix the `usePastelColorGenerator` hook public api exposing issue
- Fixes https://github.com/wso2/oxygen-ui/issues/263
- (None)
=> fix(react): fix the `usePastelColorGenerator` hook public api exposing issue

.github/ISSUE_TEMPLATE/bug_report.md, packages/primitives/src/icons/ban-16.svg, packages/primitives/src/icons/building-alt-16.svg, packages/primitives/src/icons/ellipsis-16.svg, packages/primitives/src/icons/ellipsis-vertical-16.svg, packages/primitives/src/icons/pen-to-square-16.svg, pull_request_template.md
This PR adds the following icons:
- BanIcon 
-  BuildingAltIcon 
- EllipsisIcon 
- EllipsisVerticalIcon 
- PenToSquareIcon 
- https://github.com/wso2/oxygen-ui/issues/272
- N/A
=> feat(primitives): add icons

docs/website/package.json, pnpm-lock.yaml
=> Revert "fix(website): change `@oxygen-ui/logger` to get dependency from the workspace"

pnpm-lock.yaml
=> Revert "chore(ci): update lock file"

.github/workflows/release.yml
=> Revert "ci: stick pnpm version to latest version available"

packages/react/src/components/dnd/DroppableContainer.tsx
This pull request includes changes to the `DroppableContainer` component in the `packages/react/src/components/dnd` directory to address a TypeScript issue temporarily. The most important changes include extending the `DroppableContainerProps` type with `any` and adding a TODO comment with a tracker link.
Changes to address TypeScript issue:
* [`packages/react/src/components/dnd/DroppableContainer.tsx`](diffhunk://#diff-e3a862c500df02a2d329bba58fe3b13e18e31dbda96fae5ee5de629492481c75R39-R40): Added a TODO comment mentioning the temporary workaround of extending `any` to overcome a TypeScript issue and included a tracker link for the issue.
* [`packages/react/src/components/dnd/DroppableContainer.tsx`](diffhunk://#diff-e3a862c500df02a2d329bba58fe3b13e18e31dbda96fae5ee5de629492481c75L62-R64) …
=> fix(react): fix the TS issue in `DroppableContainer`

packages/react/src/components/Avatar/Avatar.tsx, packages/react/src/components/Avatar/avatar.scss, packages/react/src/components/Header/header.scss
- This is to fix the styling inconsistency of Avatar in the Header component and UserDropdownMenu component.
- Introduced new class to match classname revamping as mentioned in https://github.com/wso2/oxygen-ui/issues/274
=> fix(react): fix style inconsistency in Header component

packages/react/README.md, pnpm-lock.yaml
$subject. This will include the pnpm and node version to be used during development
=> chore(react): Update readme

package.json, pnpm-lock.yaml
=> chore: Upgrade release-it version to 16

package.json, pnpm-lock.yaml
=> chore: stick release-it versions

.changeset/short-lies-slide.md, .github/workflows/pr-builder.yml, packages/react/src/components/DatePicker/index.ts, packages/react/src/components/DateTimePicker/index.ts, packages/react/src/components/LocalizationProvider/index.ts, packages/react/src/components/TimePicker/index.ts, packages/react/src/components/index.ts
=> chore: Fix lint errors

.changeset/tangy-falcons-fly.md, packages/react/src/components/Header/header.scss, packages/react/src/components/NavbarItem/navbar-item.scss
fix(react): Make CSS files direction-aware to support RTL layouts
=> fix(react): Make CSS files direction-aware to support RTL layouts
